// <auto-generated />
using System;
using KnowHowApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnowHowApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260817005624_AdicionaAreaInteresseUsuario")]
    partial class AdicionaAreaInteresseUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnowHowApi.Domain.Models.AreaInteresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("AreasInteresse", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologia e Programação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Idiomas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Música"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Design e Artes"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Negócios e Empreendedorismo"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Saúde e Bem-estar"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Reforço Escolar"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Outros"
                        });
                });

            modelBuilder.Entity("KnowHowApi.Domain.Models.PerfilProfessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Avaliacao")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("AvatarVariante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAvaliacoes")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PerfilProfessores", (string)null);
                });

            modelBuilder.Entity("KnowHowApi.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaInteresseId")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaInteresseId");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("[Cpf] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("KnowHowApi.Domain.Models.PerfilProfessor", b =>
                {
                    b.HasOne("KnowHowApi.Domain.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("KnowHowApi.Domain.Models.PerfilProfessor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KnowHowApi.Domain.Models.Usuario", b =>
                {
                    b.HasOne("KnowHowApi.Domain.Models.AreaInteresse", "AreaInteresse")
                        .WithMany()
                        .HasForeignKey("AreaInteresseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AreaInteresse");
                });
#pragma warning restore 612, 618
        }
    }
}
