// <auto-generated />
using System;
using KnowHowApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KnowHowApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260819000038_AddRecuperacaoSenhaUsuario")]
    partial class AddRecuperacaoSenhaUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KnowHowApi.Domain.Models.AreaInteresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("AreasInteresse", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologia e Programação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Idiomas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Música"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Design e Artes"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Negócios e Empreendedorismo"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Saúde e Bem-estar"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Reforço Escolar"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Outros"
                        });
                });

            modelBuilder.Entity("KnowHowApi.Domain.Models.PerfilProfessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnosExperiencia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("AreaEspecialidadeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Avaliacao")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("AvatarVariante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("FotoPerfil")
                        .HasColumnType("bytea");

                    b.Property<string>("FotoPerfilContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAvaliacoes")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AreaEspecialidadeId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PerfilProfessores", (string)null);
                });

            modelBuilder.Entity("KnowHowApi.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaInteresseId")
                        .HasColumnType("integer");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RecuperacaoSenhaCodigoExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecuperacaoSenhaCodigoHash")
                        .HasColumnType("text");

                    b.Property<int>("RecuperacaoSenhaTentativas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("RecuperacaoSenhaTokenExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecuperacaoSenhaTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaInteresseId");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("\"Cpf\" IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("KnowHowApi.Domain.Models.PerfilProfessor", b =>
                {
                    b.HasOne("KnowHowApi.Domain.Models.AreaInteresse", "AreaEspecialidade")
                        .WithMany()
                        .HasForeignKey("AreaEspecialidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KnowHowApi.Domain.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("KnowHowApi.Domain.Models.PerfilProfessor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaEspecialidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KnowHowApi.Domain.Models.Usuario", b =>
                {
                    b.HasOne("KnowHowApi.Domain.Models.AreaInteresse", "AreaInteresse")
                        .WithMany()
                        .HasForeignKey("AreaInteresseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AreaInteresse");
                });
#pragma warning restore 612, 618
        }
    }
}
